# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  # Boot2docker with guest additions to mount shared folders
  config.vm.box = "AlbanMontaigu/boot2docker"

  # Shared folders
  config.vm.synced_folder "../cluster-files", "/mnt/cluster-files"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1500"
     vb.cpus  = "2"
   end

  config.vm.provision "shell", privileged: false, keep_color: true, inline: <<-SHELL
        # Install bash
        tce-load -wi bash

        # SSL BUILD CONFIG
            mkdir ~/prep-ssl ~/azure

            # Replace CR when mounting mounting from windows
            tr -d "\015" < /vagrant/prep-ssl/build-cfssl.sh > ~/prep-ssl/build-cfssl.sh
            tr -d "\015" < /vagrant/prep-ssl/generate-ca.sh > ~/prep-ssl/generate-ca.sh
            tr -d "\015" < /vagrant/azure/deploy-etcd.sh > ~/azure/deploy-etcd.sh
            
            # do some links
            ln -s /mnt/cluster-files/ca-config.json ~/prep-ssl/ca-config.json 
            ln -s /mnt/cluster-files/ca-csr.json ~/prep-ssl/ca-csr.json 
            
            # Make executable
            chmod +x ~/prep-ssl/build-cfssl.sh ~/prep-ssl/generate-ca.sh
            chmod +x ~/azure/deploy-etcd.sh

        # AZURE BUILD CONFIG
        
   SHELL
end
